on:
  push
  
name: Test awscli

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify awscli
      run: aws --version
    - name: list S3 bucket
      run: aws s3 ls s3://pyphoy
