on:
  push
  
name: Test awscli

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify awscli
      run: aws --version
    - name: list bucket S#
      run: aws s3 ls s3://pyphoy
